USE MASTER
GO
IF EXISTS(SELECT * FROM SYS.DATABASES WHERE NAME='BD_SHOPMI')  
BEGIN 
ALTER DATABASE BD_SHOPMI SET SINGLE_USER 
WITH ROLLBACK IMMEDIATE
END 
GO

IF EXISTS(SELECT * FROM SYS.DATABASES WHERE NAME='BD_SHOPMI')  
BEGIN 
    USE MASTER 
    DROP DATABASE BD_SHOPMI
END 
GO

CREATE DATABASE BD_SHOPMI
GO

USE BD_SHOPMI
GO


/* TABLAS */

-- ROL
CREATE TABLE ROL
(
    CODROL INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    NOMBREROL VARCHAR(100) NOT NULL,
    ESTROL BIT NOT NULL
)
GO

-- CATEGORIA
CREATE TABLE CATEGORIA
(
    CODCATEGORIA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    IMGCATEGORIA VARCHAR(50) NOT NULL,
    NOMCATEGORIA VARCHAR(50) NOT NULL,
    ESTCATEGORIA BIT NOT NULL
)
GO

-- MARCA
CREATE TABLE MARCA
(
    CODMARCA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    NOMBREMARCA VARCHAR(25) NOT NULL,
    ESTMARCA BIT NOT NULL
)
GO

-- PRODUCTO
CREATE TABLE PRODUCTO
(
    CODPRODUCTO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    CODCATEGORIA INT NOT NULL,
    IMGPRODUCTO VARCHAR(50) NOT NULL,
    NOMPRODUCTO VARCHAR(70) NOT NULL,
    DESCRIPCION VARCHAR(300) NOT NULL,
    PREUNI DECIMAL(10, 2) NOT NULL,
    CODMARCA INT NOT NULL,
    STOCK INT NOT NULL,
    ESTPRODUCTO BIT NOT NULL,
    FOREIGN KEY (CODCATEGORIA) REFERENCES CATEGORIA(CODCATEGORIA),
    FOREIGN KEY (CODMARCA) REFERENCES MARCA(CODMARCA)
)
GO

-- DISTRITO
CREATE TABLE DISTRITO
(
    CODDISTRITO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    NOMBREDISTRITO VARCHAR(100) NOT NULL,
    CODPOSTAL VARCHAR(10) NOT NULL,
    ESTDISTRITO BIT NOT NULL
)
GO

-- CLIENTE
CREATE TABLE CLIENTE
(
    CODCLIENTE INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    NUMEROCOMDOCUMENTO CHAR(8) NOT NULL,
    APELLIDOS VARCHAR(50) NOT NULL,
    NOMBRES VARCHAR(50) NOT NULL,
    CODDISTRITO INT NOT NULL,
    DIRECCION VARCHAR(150) NOT NULL,
    FECNAC DATE NOT NULL,
    SEXO CHAR(1) NOT NULL,
    CORREO VARCHAR(50) NOT NULL,
	TELEFONO CHAR(9) NOT NULL,
    ESTCLIENTE BIT NOT NULL,
    FOREIGN KEY (CODDISTRITO) REFERENCES DISTRITO(CODDISTRITO)
)
GO

-- EMPLEADO
CREATE TABLE EMPLEADO
(
    CODEMPLEADO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    NUMERODOCUMENTO CHAR(8) NOT NULL,
    APELLIDOS VARCHAR(50) NOT NULL,
    NOMBRES VARCHAR(50) NOT NULL,
    CODDISTRITO INT NOT NULL,
    DIRECCION VARCHAR(150) NOT NULL,
    FECNAC DATE NOT NULL,
	SEXO CHAR(1) NOT NULL,
    CORREO VARCHAR(50) NOT NULL,
    ESTEMPLEADO BIT NOT NULL,
    FOREIGN KEY (CODDISTRITO) REFERENCES DISTRITO(CODDISTRITO)
)
GO

-- USUARIO
CREATE TABLE USUARIO
(
	CODUSUARIO INT IDENTITY PRIMARY KEY NOT NULL,
	APEUSUARIO VARCHAR(50) NOT NULL,
	NOMUSUARIO VARCHAR(50) NOT NULL,
	CORUSUARIO VARCHAR(100) NOT NULL,
	CONUSUARIO VARCHAR(50) NOT NULL,
	FECCRE DATETIME NOT NULL DEFAULT GETDATE(),
	ESTUSUARIO BIT NOT NULL,
	CODEMPLEADO INT NULL FOREIGN KEY (CODEMPLEADO) REFERENCES EMPLEADO(CODEMPLEADO),
	CODROL INT FOREIGN KEY (CODROL) REFERENCES ROL(CODROL)
)
GO

-- PEDIDO
CREATE TABLE PEDIDO
(
    CODPEDIDO INT IDENTITY PRIMARY KEY NOT NULL,
    CODCLIENTE INT NOT NULL,
    CODEMPLEADO INT NOT NULL,
    FECPED DATE NOT NULL,
	PRECIOTOTAL DECIMAL,
	ACTPED VARCHAR(20) NOT NULL,
	ESTPED BIT NOT NULL,
    FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTE(CODCLIENTE),
    FOREIGN KEY (CODEMPLEADO) REFERENCES EMPLEADO(CODEMPLEADO)
)
GO

-- DETALLEPEDIDO
CREATE TABLE DETALLEPEDIDO
(
	CODPEDIDO INT NOT NULL FOREIGN KEY (CODPEDIDO) REFERENCES PEDIDO,
	CODPRODUCTO INT NOT NULL FOREIGN KEY (CODPRODUCTO) REFERENCES PRODUCTO,
	PREUNI DECIMAL(10, 2) NOT NULL,
	CANTIDAD INT NOT NULL,
	EST_PP BIT NOT NULL
	PRIMARY KEY(CODPEDIDO, CODPRODUCTO)
)