USE MASTER
GO
IF EXISTS(SELECT * FROM SYS.DATABASES WHERE NAME='BD_SHOPMI')  
BEGIN 
ALTER DATABASE BD_SHOPMI SET SINGLE_USER 
WITH ROLLBACK IMMEDIATE
END 
GO

IF EXISTS(SELECT * FROM SYS.DATABASES WHERE NAME='BD_SHOPMI')  
BEGIN 
    USE MASTER 
    DROP DATABASE BD_SHOPMI
END 
GO

CREATE DATABASE BD_SHOPMI
GO

USE BD_SHOPMI
GO


/* TABLAS */

-- ROL
CREATE TABLE ROL
(
    CODROL INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    NOMBREROL VARCHAR(100) NOT NULL,
    ESTROL BIT NOT NULL
)
GO

-- USUARIO
CREATE TABLE USUARIO
(
	CODUSUARIO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NUMERODOCUMENTO CHAR(8) NOT NULL,
	APEUSUARIO VARCHAR(50) NOT NULL,
	NOMUSUARIO VARCHAR(50) NOT NULL,
	FECNAC DATE NOT NULL,
	SEXUSUARIO CHAR(1) NOT NULL,
	TELUSUARIO CHAR(9) NOT NULL,
	CORUSUARIO VARCHAR(80) NOT NULL,
	CONUSUARIO VARCHAR(50) NOT NULL,
	FECCRE DATETIME NOT NULL DEFAULT GETDATE(),
	ESTUSUARIO BIT NOT NULL,
	CODROL INT NOT NULL,
	FOREIGN KEY (CODROL) REFERENCES ROL
)
GO

-- CATEGORIA
CREATE TABLE CATEGORIA
(
    CODCATEGORIA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    IMGCATEGORIA VARCHAR(50) NOT NULL,
    NOMCATEGORIA VARCHAR(50) NOT NULL,
    ESTCATEGORIA BIT NOT NULL
)
GO

-- MARCA
CREATE TABLE MARCA
(
    CODMARCA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    NOMBREMARCA VARCHAR(25) NOT NULL,
    ESTMARCA BIT NOT NULL
)
GO

-- PRODUCTO
CREATE TABLE PRODUCTO
(
    CODPRODUCTO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    CODCATEGORIA INT NOT NULL,
    IMGPRODUCTO VARCHAR(50) NOT NULL,
    NOMPRODUCTO VARCHAR(70) NOT NULL,
    DESCRIPCION VARCHAR(300) NOT NULL,
    PREUNI DECIMAL(10, 2) NOT NULL,
    CODMARCA INT NOT NULL,
    STOCK INT NOT NULL,
    ESTPRODUCTO BIT NOT NULL,
    FOREIGN KEY (CODCATEGORIA) REFERENCES CATEGORIA,
    FOREIGN KEY (CODMARCA) REFERENCES MARCA
)
GO

-- PEDIDO
CREATE TABLE PEDIDO
(
    CODPEDIDO INT IDENTITY PRIMARY KEY NOT NULL,
    CODUSUARIO INT NOT NULL,
    FECPED DATE NOT NULL,
	PRECIOTOTAL DECIMAL NOT NULL,
	ACTPED VARCHAR(20) NOT NULL,
	ESTPED BIT NOT NULL,
    FOREIGN KEY (CODUSUARIO) REFERENCES USUARIO
)
GO

-- DETALLEPEDIDO
CREATE TABLE DETALLEPEDIDO
(
	CODPEDIDO INT NOT NULL,
	CODPRODUCTO INT NOT NULL,
	PREUNI DECIMAL(10, 2) NOT NULL,
	CANTIDAD INT NOT NULL,
	EST_PP BIT NOT NULL
	PRIMARY KEY(CODPEDIDO, CODPRODUCTO),
	FOREIGN KEY (CODPEDIDO) REFERENCES PEDIDO,
	FOREIGN KEY (CODPRODUCTO) REFERENCES PRODUCTO
)
GO

CREATE TABLE PAGO
(
	CODPAGO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	CODPEDIDO INT NOT NULL,
	MONTOPAGO DECIMAL(10, 2) NOT NULL,
	FECPAGO DATE NOT NULL DEFAULT GETDATE(),
	METPAGO CHAR(2) NOT NULL,
	ESTPAGO BIT NOT NULL,
	FOREIGN KEY (CODPEDIDO) REFERENCES PEDIDO
)
GO

-- DISTRITO
CREATE TABLE DISTRITO
(
    CODDISTRITO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    NOMBREDISTRITO VARCHAR(50) NOT NULL,
    CODPOSTAL VARCHAR(10) NOT NULL,
    ESTDISTRITO BIT NOT NULL
)
GO

-- SUCURSAL
CREATE TABLE SUCURSAL
(
    CODSUCURSAL INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    NOMSUCURSAL VARCHAR(50) NOT NULL,
    DIRSUCURSAL VARCHAR(70) NOT NULL,
	ESTSUCURSAL BIT NOT NULL,
    CODDISTRITO INT NOT NULL,
	FOREIGN KEY (CODDISTRITO) REFERENCES DISTRITO
)
GO

-- RECOJO
CREATE TABLE RECOJO
(
	CODPEDIDO INT PRIMARY KEY,
	CODSUCURSAL INT NOT NULL,
	FECRECOJO DATE NOT NULL,
	FOREIGN KEY (CODPEDIDO) REFERENCES PEDIDO,
	FOREIGN KEY (CODSUCURSAL) REFERENCES SUCURSAL
);

-- ENVIO
CREATE TABLE ENVIO
(
	CODPEDIDO INT PRIMARY KEY,
	FECENVIO DATE NOT NULL,
	ACTENVIO VARCHAR(30) NOT NULL,
	DIRENVIO VARCHAR(255) NOT NULL,
	CODDISTRITO INT NOT NULL,
	FOREIGN KEY (CODPEDIDO) REFERENCES PEDIDO,
	FOREIGN KEY (CODDISTRITO) REFERENCES DISTRITO
);

/* RESTRICCIONES */

--EL METODO DE PAGO ADMITA TC: TARJETA DE CREDITO, TB: TRANSFERENCIA BANCARIA, E: EFECTIVO, TD: TARJETA DE DEBITO
ALTER TABLE PAGO
ADD CONSTRAINT CHK_METPAGO
CHECK (METPAGO IN('TC', 'TB','E', 'TD'))